/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
/**
 *
 * @author leonel
 */
public class Vista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista.class.getName());
    
    // 1. Declaramos el controlador
    private Controlador controlador;

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        
        this.controlador = new Controlador();
        this.setTitle("Sistema de Reclutamiento TI");
        this.setLocationRelativeTo(null); // Centrar en pantalla
        
        construirMenuRapido();
    }
    
    private void construirMenuRapido() {
        // Creamos un panel con un layout de cuadrícula para los botones
        JPanel panelMenu = new JPanel(new GridLayout(5, 1, 10, 10));
        panelMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        JButton btnEmpresa = new JButton("1. Registrar Empresa");
        JButton btnOferta = new JButton("2. Publicar Oferta");
        JButton btnCandidato = new JButton("3. Registrar Candidato");
        JButton btnPostular = new JButton("4. Aplicar a Oferta");
        JButton btnSalir = new JButton("5. Salir");
        
        // Agregamos eventos básicos para simular la vista (Módulos en construcción por tiempo)
        btnEmpresa.addActionListener(e -> JOptionPane.showMessageDialog(this, "[Módulo en construcción: Registro de Empresa]\nControlador conectado correctamente."));
        btnOferta.addActionListener(e -> JOptionPane.showMessageDialog(this, "[Módulo en construcción: Publicar Oferta]"));
        btnCandidato.addActionListener(e -> JOptionPane.showMessageDialog(this, "[Módulo en construcción: Registrar Candidato]"));
        btnPostular.addActionListener(e -> JOptionPane.showMessageDialog(this, "[Módulo en construcción: Postulación]"));
        btnSalir.addActionListener(e -> System.exit(0));
        
        // Añadimos los botones al panel
        panelMenu.add(btnEmpresa);
        panelMenu.add(btnOferta);
        panelMenu.add(btnCandidato);
        panelMenu.add(btnPostular);
        panelMenu.add(btnSalir);
        
        // Reemplazamos el contenido de la ventana con nuestro panel
        this.setContentPane(panelMenu);
        this.setSize(350, 400); // Forzamos un tamaño adecuado
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Vista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
